apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env: #setting env variables for the containers
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
